encuesta/urls.py
from django.urls import path

from . import views 

app_name = 'encuesta'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:region_id>/', views.detalle, name='detalle'),
    path('<int:region_id>/resultados/', views.resultados, name='resultados'),
    path('<int:region_id>/voto/', views.votar, name='votar'),

]

votacion/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('encuesta/', include('encuesta.urls')),
    path('admin/', admin.site.urls),
]

encuesta/models.py
from django.db import models

# Create your models here.

class Region(models.Model):
    region_opcion = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

class Opcion(models.Model):
    region = models.ForeignKey(Region, on_delete=models.CASCADE)
    candidato = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)

encuesta/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse 

from .models import Opcion, Region
# Create your views here.

def index(request):
    latest_question_list = Region.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'encuesta/index.html', context)

def detalle(request, region_id):
    region = get_object_or_404(Region, pk=region_id)
    return render(request, 'encuesta/detalle.html', {'region': region})

def votar(request, region_id):
    region = get_object_or_404(Region, pk=region_id)
    try:
        selected_opcion = region.opcion_set.get(pk=request.POST['opcion'])
    except (KeyError, Opcion.DoesNotExist):
        return render(request, 'encuesta/detalle.html',{
            'region': region,
            'error_message': "No has seleccionado una opcion.",
        })
    else: 
        selected_opcion.votos += 1 
        selected_opcion.save()
        return HttpResponseRedirect(reverse('encuesta:resultados', args=(region.id,)))

def resultados(request, region_id):
    region = get_object_or_404(Region, pk=region_id)
    return render(request, 'encuesta/resultados.html',{'region':region})

encuesta/templates/encuesta/detalle.html
<meta http-equiv=”Content-Type” content=”text/html; charset=UTF-8″ />
<h1>{{ region.region_opcion }}</h1>

<ul>
{% for opcion in region.opcion_set.all %}
    <li>{{ opcion.candidato }} -- {{ opcion.votos }} voto{{ opcion.votos|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'encuesta:resultados' region.id%}">Votar de nuevo?</a>
<a href="{% url 'encuesta:index' %}">Ver preguntas</a>

encuesta/templates/encuesta/index.html
<meta http-equiv=”Content-Type” content=”text/html; charset=UTF-8″ />
<h1>Encuesta</h1>

{% if latest_question_list %}
    <ul>
    {% for region in latest_question_list %}
        <li>
            <a href="/encuesta/{{ region.id }}/">{{ region.region_opcion }}</a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No hay resgistros.</p>
{% endif %}

encuesta/templates/encuesta/resultados.html
<meta http-equiv=”Content-Type” content=”text/html; charset=UTF-8″ />
<h1>{{ region.region_opcion }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'encuesta:votar' region.id %}" method="post">
{% csrf_token %}
{% for opcion in region.opcion_set.all %}
    <input type="radio" name="opcion" id="opcion{{ forloop.counter }}" value="{{ opcion.id }}">
    <label for="opcion{{ forloop.counter }}">{{ opcion.candidato }}</label><br>
{% endfor %}    
<input type="submit" value="Votar">    
</form>
<br/>
<a href="{% url 'encuesta:index' %}">Ver regiones</a>